"""add opex_items table for OPEX breakdown

Revision ID: 0bd00f1c9b93
Revises: e3be6ed2aeaa
Create Date: 2026-04-10 07:02:07.850087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd00f1c9b93'
down_revision: Union[str, None] = 'e3be6ed2aeaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opex_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_plan_id'], ['project_financial_plans.id'], name=op.f('fk_opex_items_financial_plan_id_project_financial_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opex_items')),
    sa.UniqueConstraint('financial_plan_id', 'name', name='uq_opex_items_plan_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opex_items')
    # ### end Alembic commands ###
