"""B-12 B-13 AKB and OBPPC tables

Revision ID: 196823092dd6
Revises: ec721a2bf16d
Create Date: 2026-04-10 09:48:57.785078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196823092dd6'
down_revision: Union[str, None] = 'ec721a2bf16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('universe_outlets', sa.Integer(), nullable=True),
    sa.Column('target_outlets', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('weighted_distribution', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_akb_entries_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_akb_entries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_akb_entries')),
    sa.UniqueConstraint('project_id', 'channel_id', name='uq_akb_entries_project_channel')
    )
    op.create_table('obppc_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.String(length=200), nullable=True),
    sa.Column('price_tier', sa.String(length=50), nullable=False),
    sa.Column('pack_format', sa.String(length=100), nullable=False),
    sa.Column('pack_size_ml', sa.Integer(), nullable=True),
    sa.Column('price_point', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("price_tier IN ('premium', 'mainstream', 'value')", name=op.f('ck_obppc_entries_ck_obppc_entries_price_tier')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_obppc_entries_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_obppc_entries_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_obppc_entries_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obppc_entries')),
    sa.UniqueConstraint('project_id', 'sku_id', 'channel_id', 'pack_format', name='uq_obppc_entries_project_sku_channel_pack')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obppc_entries')
    op.drop_table('akb_entries')
    # ### end Alembic commands ###
