"""initial schema

Revision ID: 1c05696e13e6
Revises: 
Create Date: 2026-04-08 05:36:15.792480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c05696e13e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('universe_outlets', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('code', name=op.f('uq_channels_code'))
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('monthly', 'annual', name='period_type', native_enum=False, length=20), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('month_num', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periods')),
    sa.UniqueConstraint('period_number', name='uq_periods_period_number')
    )
    op.create_table('ref_inflation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('month_coefficients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_inflation')),
    sa.UniqueConstraint('profile_name', name=op.f('uq_ref_inflation_profile_name'))
    )
    op.create_table('ref_seasonality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('month_coefficients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_seasonality')),
    sa.UniqueConstraint('profile_name', name=op.f('uq_ref_seasonality_profile_name'))
    )
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('volume_l', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('package_type', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('wacc', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('wc_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inflation_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inflation_profile_id'], ['ref_inflation.id'], name=op.f('fk_projects_inflation_profile_id_ref_inflation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('project_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.Column('production_cost_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('ca_m_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('marketing_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_skus_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_project_skus_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_skus')),
    sa.UniqueConstraint('project_id', 'sku_id', name='uq_project_skus_project_sku')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('base', 'conservative', 'aggressive', name='scenario_type', native_enum=False, length=20), nullable=False),
    sa.Column('delta_nd', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('delta_offtake', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('delta_opex', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenarios_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios')),
    sa.UniqueConstraint('project_id', 'type', name='uq_scenarios_project_type')
    )
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_sku_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=500), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('loss_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_sku_id'], ['project_skus.id'], name=op.f('fk_bom_items_project_sku_id_project_skus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_items'))
    )
    op.create_table('project_sku_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_sku_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('nd_target', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('nd_ramp_months', sa.Integer(), nullable=False),
    sa.Column('offtake_target', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('channel_margin', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('promo_discount', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('promo_share', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('shelf_price_reg', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('logistics_cost_per_kg', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('seasonality_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_project_sku_channels_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_sku_id'], ['project_skus.id'], name=op.f('fk_project_sku_channels_project_sku_id_project_skus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seasonality_profile_id'], ['ref_seasonality.id'], name=op.f('fk_project_sku_channels_seasonality_profile_id_ref_seasonality'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_sku_channels')),
    sa.UniqueConstraint('project_sku_id', 'channel_id', name='uq_psk_channels_project_sku_channel')
    )
    op.create_table('scenario_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('period_scope', sa.Enum('y1y3', 'y1y5', 'y1y10', name='period_scope', native_enum=False, length=10), nullable=False),
    sa.Column('npv', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('irr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('payback_simple', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('payback_discounted', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('contribution_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('go_no_go', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_results_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_results')),
    sa.UniqueConstraint('scenario_id', 'period_scope', name='uq_scenario_results_scenario_scope')
    )
    op.create_table('period_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_channel_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.Enum('predict', 'finetuned', 'actual', name='source_type', native_enum=False, length=20), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name=op.f('fk_period_values_period_id_periods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['psk_channel_id'], ['project_sku_channels.id'], name=op.f('fk_period_values_psk_channel_id_project_sku_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_period_values_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_values')),
    sa.UniqueConstraint('psk_channel_id', 'scenario_id', 'period_id', 'source_type', 'version_id', name='uq_period_values_unique_layer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_values')
    op.drop_table('scenario_results')
    op.drop_table('project_sku_channels')
    op.drop_table('bom_items')
    op.drop_table('scenarios')
    op.drop_table('project_skus')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('skus')
    op.drop_table('ref_seasonality')
    op.drop_table('ref_inflation')
    op.drop_table('periods')
    op.drop_table('channels')
    # ### end Alembic commands ###
