"""phase 4.5 passport content fields + media assets

Revision ID: 2e7b824682be
Revises: 34aad4c7c120
Create Date: 2026-04-09 12:07:40.937399

Фаза 4.5 (контент паспорта):
- 16 scalar полей в projects (description, gate_stage CHECK G0..G5,
  passport_date, project_owner, project_goal, innovation_type, geography,
  production_type, growth_opportunity, concept_text, rationale, idea_short,
  target_audience, replacement_target, technology, rnd_progress,
  executive_summary)
- 5 JSONB полей в projects (risks, validation_tests, function_readiness,
  roadmap_tasks, approvers)
- ProjectSKU.package_image_id FK → media_assets.id (ON DELETE SET NULL)
- Новая таблица media_assets для file storage backend (4.5.2)

Все новые поля nullable — backward compat для существующих проектов
(до Discovery V2 GORJI / тестовых проектов). Заполняются вручную в
table «Содержание» (4.5.3) или через AI генерацию (Phase 7.6/7.7/7.8).

CHECK constraint `ck_projects_gate_stage` добавлен руками после autogen
(Alembic не подхватывает table-level CheckConstraint при ALTER TABLE).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e7b824682be'
down_revision: Union[str, None] = '34aad4c7c120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("kind IN ('package_image', 'concept_design', 'other')", name=op.f('ck_media_assets_ck_media_assets_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_media_assets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_assets_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.add_column('project_skus', sa.Column('package_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_project_skus_package_image_id_media_assets'), 'project_skus', 'media_assets', ['package_image_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('gate_stage', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('passport_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('project_owner', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('project_goal', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('innovation_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('geography', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('production_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('growth_opportunity', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('concept_text', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('idea_short', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('replacement_target', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('technology', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('rnd_progress', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('validation_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('function_readiness', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('roadmap_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('approvers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # CHECK constraint для gate_stage (добавлен вручную, autogen пропускает
    # table-level constraints при ALTER TABLE existing).
    op.create_check_constraint(
        'ck_projects_gate_stage',
        'projects',
        "gate_stage IS NULL OR gate_stage IN ('G0', 'G1', 'G2', 'G3', 'G4', 'G5')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_projects_gate_stage', 'projects', type_='check')
    op.drop_column('projects', 'approvers')
    op.drop_column('projects', 'roadmap_tasks')
    op.drop_column('projects', 'function_readiness')
    op.drop_column('projects', 'validation_tests')
    op.drop_column('projects', 'risks')
    op.drop_column('projects', 'executive_summary')
    op.drop_column('projects', 'rnd_progress')
    op.drop_column('projects', 'technology')
    op.drop_column('projects', 'replacement_target')
    op.drop_column('projects', 'target_audience')
    op.drop_column('projects', 'idea_short')
    op.drop_column('projects', 'rationale')
    op.drop_column('projects', 'concept_text')
    op.drop_column('projects', 'growth_opportunity')
    op.drop_column('projects', 'production_type')
    op.drop_column('projects', 'geography')
    op.drop_column('projects', 'innovation_type')
    op.drop_column('projects', 'project_goal')
    op.drop_column('projects', 'project_owner')
    op.drop_column('projects', 'passport_date')
    op.drop_column('projects', 'gate_stage')
    op.drop_column('projects', 'description')
    op.drop_constraint(op.f('fk_project_skus_package_image_id_media_assets'), 'project_skus', type_='foreignkey')
    op.drop_column('project_skus', 'package_image_id')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
