"""add cm_threshold to project

Revision ID: 32c6c1bd0abf
Revises: 7b303e6b7b59
Create Date: 2026-04-13 16:38:29.719527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c6c1bd0abf'
down_revision: Union[str, None] = '7b303e6b7b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cm_threshold', sa.Numeric(precision=8, scale=6), server_default='0.250000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cm_threshold')
    # ### end Alembic commands ###
