"""add category column to opex_items

Revision ID: 338f0a242518
Revises: df5babcd77d8
Create Date: 2026-04-11 05:18:19.854653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338f0a242518'
down_revision: Union[str, None] = 'df5babcd77d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opex_items', sa.Column('category', sa.String(length=50), server_default='other', nullable=False))
    op.drop_constraint(op.f('uq_opex_items_plan_name'), 'opex_items', type_='unique')
    op.create_unique_constraint('uq_opex_items_plan_category_name', 'opex_items', ['financial_plan_id', 'category', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_opex_items_plan_category_name', 'opex_items', type_='unique')
    op.create_unique_constraint(op.f('uq_opex_items_plan_name'), 'opex_items', ['financial_plan_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('opex_items', 'category')
    # ### end Alembic commands ###
