"""rollback launch year month from psk to psc

Revision ID: 34aad4c7c120
Revises: a5aeae3eb4bb
Create Date: 2026-04-09 05:11:36.258206

D-13 architectural fix: Excel хранит launch_year/launch_month per
(SKU × Channel), не per SKU. Первая итерация (a5aeae3eb4bb) поместила
поля на ProjectSKU — неверно. Эта миграция переносит на ProjectSKUChannel.

Data-loss-safe: предыдущая миграция была применена недавно (коммит
eb8426d), production-данных нет, все строки project_skus имеют
launch_year=launch_month=1 (default). Новые столбцы PSC получают
тот же default через server_default=1.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34aad4c7c120'
down_revision: Union[str, None] = 'a5aeae3eb4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_sku_channels', sa.Column('launch_year', sa.Integer(), server_default='1', nullable=False))
    op.add_column('project_sku_channels', sa.Column('launch_month', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('project_skus', 'launch_month')
    op.drop_column('project_skus', 'launch_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_skus', sa.Column('launch_year', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('project_skus', sa.Column('launch_month', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('project_sku_channels', 'launch_month')
    op.drop_column('project_sku_channels', 'launch_year')
    # ### end Alembic commands ###
