"""phase_7_5_ai_budget_and_user_id

Revision ID: 4160c5e248b5
Revises: 727f2e61e414
Create Date: 2026-04-10 05:29:50.769186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4160c5e248b5'
down_revision: Union[str, None] = '727f2e61e414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_ai_usage_log_user_id_users'), 'ai_usage_log', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('ai_budget_rub_monthly', sa.Numeric(precision=12, scale=2), server_default='500.00', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ai_budget_rub_monthly')
    op.drop_constraint(op.f('fk_ai_usage_log_user_id_users'), 'ai_usage_log', type_='foreignkey')
    op.drop_column('ai_usage_log', 'user_id')
    # ### end Alembic commands ###
