"""add production_mode and copacking_rate to project_skus

Revision ID: 6c10a01c69c0
Revises: 32c6c1bd0abf
Create Date: 2026-04-13 17:14:04.062035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c10a01c69c0'
down_revision: Union[str, None] = '32c6c1bd0abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_skus', sa.Column('production_mode', sa.String(length=20), server_default='own', nullable=False))
    op.add_column('project_skus', sa.Column('copacking_rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_skus', 'copacking_rate')
    op.drop_column('project_skus', 'production_mode')
    # ### end Alembic commands ###
