"""phase_7_4_ai_executive_summary_fields

Revision ID: 727f2e61e414
Revises: c341fb0685fe
Create Date: 2026-04-10 04:49:00.546857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '727f2e61e414'
down_revision: Union[str, None] = 'c341fb0685fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ai_executive_summary', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('ai_kpi_commentary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('ai_commentary_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('ai_commentary_updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_projects_ai_commentary_updated_by_users'), 'projects', 'users', ['ai_commentary_updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_ai_commentary_updated_by_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'ai_commentary_updated_by')
    op.drop_column('projects', 'ai_commentary_updated_at')
    op.drop_column('projects', 'ai_kpi_commentary')
    op.drop_column('projects', 'ai_executive_summary')
    # ### end Alembic commands ###
