"""add supplier_quotes JSONB to projects

Revision ID: 7b303e6b7b59
Revises: 84d5e23d52e8
Create Date: 2026-04-11 05:56:52.315694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b303e6b7b59'
down_revision: Union[str, None] = '84d5e23d52e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('supplier_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'supplier_quotes')
    # ### end Alembic commands ###
