"""add project soft delete

Revision ID: 7efc99156f7e
Revises: 1c05696e13e6
Create Date: 2026-04-08 06:43:59.059194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efc99156f7e'
down_revision: Union[str, None] = '1c05696e13e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
