"""add project_sku launch year month

Revision ID: a5aeae3eb4bb
Revises: 65003c0135cc
Create Date: 2026-04-08 17:19:15.528725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5aeae3eb4bb'
down_revision: Union[str, None] = '65003c0135cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_skus', sa.Column('launch_year', sa.Integer(), server_default='1', nullable=False))
    op.add_column('project_skus', sa.Column('launch_month', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_skus', 'launch_month')
    op.drop_column('project_skus', 'launch_year')
    # ### end Alembic commands ###
