"""add ai_sensitivity_commentary column

Revision ID: bf144a47ef42
Revises: 5ea6751815a1
Create Date: 2026-04-10 20:26:16.901059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf144a47ef42'
down_revision: Union[str, None] = '5ea6751815a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ai_sensitivity_commentary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('projects', 'innovation_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'geography',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'production_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'production_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('projects', 'geography',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('projects', 'innovation_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('projects', 'ai_sensitivity_commentary')
    # ### end Alembic commands ###
