"""phase 7.1 ai_usage_log table

Revision ID: c341fb0685fe
Revises: 2e7b824682be
Create Date: 2026-04-09 16:16:32.834541

Phase 7.1 (Polza AI базовая инфраструктура, ADR-16):
- Новая таблица ai_usage_log — журнал вызовов Polza AI для cost
  monitoring и debugging. Колонки: project_id (nullable FK projects
  SET NULL), endpoint, model, prompt_tokens, completion_tokens,
  cost_rub (nullable Numeric(12,6)), latency_ms, error (nullable text),
  created_at.
- Таблица создаётся в 7.1, но активное логирование подключается
  только в 7.5 — endpoint'ы из 7.2..7.4 будут писать сюда после
  каждого вызова ai_service.complete_json. Phase 7.5 также добавит
  budget enforcement (Project.ai_budget_rub_monthly).
- project_id nullable на случай будущих admin-операций без привязки
  к конкретному проекту. Для 7.2..7.8 заполняется всегда.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c341fb0685fe'
down_revision: Union[str, None] = '2e7b824682be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_rub', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_usage_log_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
