"""add ingredients catalog and price history

Revision ID: dad2913e9777
Revises: ebd9ab2577f2
Create Date: 2026-04-10 08:32:16.591047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad2913e9777'
down_revision: Union[str, None] = 'ebd9ab2577f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("category IN ('raw_material', 'packaging', 'other')", name=op.f('ck_ingredients_ck_ingredients_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('name', name=op.f('uq_ingredients_name'))
    )
    op.create_table('ingredient_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredient_prices_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_prices'))
    )
    op.add_column('bom_items', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_bom_items_ingredient_id_ingredients'), 'bom_items', 'ingredients', ['ingredient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bom_items_ingredient_id_ingredients'), 'bom_items', type_='foreignkey')
    op.drop_column('bom_items', 'ingredient_id')
    op.drop_table('ingredient_prices')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
