"""phase_7_8_ai_generated_images_and_media_kind

Revision ID: e3be6ed2aeaa
Revises: ecf52051757c
Create Date: 2026-04-10 06:21:58.429355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3be6ed2aeaa'
down_revision: Union[str, None] = 'ecf52051757c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_sku_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('reference_asset_id', sa.Integer(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('art_direction', sa.Text(), nullable=False),
    sa.Column('cost_rub', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ai_generated_images_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_ai_generated_images_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_sku_id'], ['project_skus.id'], name=op.f('fk_ai_generated_images_project_sku_id_project_skus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_asset_id'], ['media_assets.id'], name=op.f('fk_ai_generated_images_reference_asset_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generated_images'))
    )
    # Update media_assets kind CHECK constraint to include new types
    op.drop_constraint('ck_media_assets_kind', 'media_assets', type_='check')
    op.create_check_constraint(
        'ck_media_assets_kind',
        'media_assets',
        "kind IN ('package_image', 'concept_design', 'ai_reference', 'ai_generated', 'other')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_media_assets_kind', 'media_assets', type_='check')
    op.create_check_constraint(
        'ck_media_assets_kind',
        'media_assets',
        "kind IN ('package_image', 'concept_design', 'other')",
    )
    op.drop_table('ai_generated_images')
    # ### end Alembic commands ###
