"""add scenario_channel_deltas for per-SKU-channel deltas

Revision ID: ebd9ab2577f2
Revises: 0bd00f1c9b93
Create Date: 2026-04-10 07:27:38.452167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd9ab2577f2'
down_revision: Union[str, None] = '0bd00f1c9b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_channel_deltas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('psk_channel_id', sa.Integer(), nullable=False),
    sa.Column('delta_nd', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('delta_offtake', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['psk_channel_id'], ['project_sku_channels.id'], name=op.f('fk_scenario_channel_deltas_psk_channel_id_project_sku_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_channel_deltas_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_channel_deltas')),
    sa.UniqueConstraint('scenario_id', 'psk_channel_id', name='uq_scenario_channel_deltas_scenario_psc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_channel_deltas')
    # ### end Alembic commands ###
