"""add region to channels

Revision ID: ec721a2bf16d
Revises: dad2913e9777
Create Date: 2026-04-10 09:11:40.110412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec721a2bf16d'
down_revision: Union[str, None] = 'dad2913e9777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'region')
    # ### end Alembic commands ###
