"""phase_7_7_marketing_research_jsonb

Revision ID: ecf52051757c
Revises: 4160c5e248b5
Create Date: 2026-04-10 06:04:02.804132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf52051757c'
down_revision: Union[str, None] = '4160c5e248b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('marketing_research', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'marketing_research')
    # ### end Alembic commands ###
